### ISSUE TITLE
Script for cmoa.jp

### ISSUE THREAD

**Issue by ker0r0** [xuzhengyi1995/Renta_Downloader#5]
If possible, I would grateful if you could make a script for cmoa.jp. Please consider it. Thanks.

**Comment by xuzhengyi1995** [comment]
Thank you for your suggestion.
I will consider to make a script using `selenium` and it can support any manga website by just adding some rules.
Because all the websites are the same things if we use Website Automated Testing framework, the things we should do are like below: 
<pre>
+------------+     +-----------+      +------------+      +-------------------+    +--------------+
|            |     |           |      |            |      |                   |OVER|              |
|   Login    +-----+ Load page +----->+ Save image +----->+ Move to next page +----+   Finished   |
|            |     |           |      |            |      |                   |    |              |
+------------+     +-----------+      +-----+------+      +---------+---------+    +--------------+
                                            ^                       |
                                            |                       |
                                            |      More page        |
                                            +-----------------------+
</pre>

This could be slower than something like Renta_Downloader, but it is much more easier and quicker to implement.

Thank you!

**Comment by ker0r0** [comment]
Wow, that’s cool. I’m looking forward to it. Please take your time :)

**Comment by xuzhengyi1995** [comment]
> Wow, that’s cool. I’m looking forward to it. Please take your time :)

I have finished this, you can check it [here](https://github.com/xuzhengyi1995/Manga_downloader).

I can not buy manga on this website, I only tried the free Manga and it works.

If there is some thing wrong with the paid manga, please let me know.

Thank you!

**Comment by ker0r0** [comment]
Hey, xuzhengyi1995. You’re the BEST!!!!
It works perfectly for a paid manga I bought and this is a superb script I've never seen.

But one more thing, I would like you to modify this program for changing the file name to three digits. I am very grateful to you.

**Comment by xuzhengyi1995** [comment]
> Hey, xuzhengyi1995. You’re the BEST!!!!
> It works perfectly for a paid manga I bought and this is a superb script I've never seen.
> 
> But one more thing, I would like you to modify this program for changing the file name to three digits. I am very grateful to you.

Thank you for liking it :)

Sorry I always forget the problem of filename.

I have updated the script, you can now change the file name prefix and number of digits by changing `file_name_prefix` and `number_of_digits`.

For example, if you are downloading Kill La Kill Manga Volume 1, and you want the file name like:

<pre>
    KLK_V1
    │--KLK_V1_001.jpg
    │--KLK_V1_002.jpg
    │--KLK_V1_003.jpg
</pre>

Then you can set the parameters like below:

```python
settings = {
    ...,
    'file_name_prefix': 'KLK_V1',
    # File name digits count, if you want your file name like '001.jpg', write 3 here.
    'number_of_digits': 3
}
```

If you have any other problem, please do not hesitate to reply or create an new issue~

Thank you!

**Comment by ker0r0** [comment]
Don't be sorry, it works fine for me. You made my day.
Thank you so much for your kindness.
